### ISSUE TITLE
Expand the build matrix

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/geos-feedstock#4]
Because we are using features this should be build for each python version out there, correct?

``` yaml
  matrix:
    - TARGET_ARCH: x86
    - TARGET_ARCH: x64
```

@pelson are you planning on a `MNT` PR to fix that?
